version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres_mr
    restart: always
    environment:
      POSTGRES_DB: mr_banco_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootdba
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  pgadmin:
  
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres      

  app:
    build: .
    container_name: spring_app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mr_banco_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: rootdba
    ports:
      - "8080:8080"

volumes:
  postgres_data:

